### ISSUE TITLE
NavBar is broken

### ISSUE THREAD

**Issue by muneebulrehman** [Nemwel-Boniface/awesomeBooksModules#2]
Hey. Good job with the project. However, I see a few issues with the live preview.
- The navbar is not working, and also luxon library used is not evaluated. Try to fix that.
- Instead of having the scroll on overflow you can change the positioning of the footer with the content of the active page.

**Comment by Nemwel-Boniface** [comment]
Hello @muneebulrehman, Thank you for spotting this. 
I had an issue with the Luxon LIbrary import but it is sorted now.
