### ISSUE TITLE
Live Demo

### ISSUE THREAD

**Issue by Thermiee** [Nemwel-Boniface/awesomeBooksModules#3]
Hello @Nemwel-Boniface I was going through your live demo and I realized your app is broken here is the: 

- The form is not adding books 
- Navbar doesn't change the view.
- List of books is not been displayed

**Comment by Nemwel-Boniface** [comment]
Hello @Thermiee, thank you for pointing this out to me. I had an issue with the Luxon Library when hosted on Github pages. It was the one blocking the functioning of the project.
I have disabled it for now and I am to refactor that functionality.
You can check it out now all the other functionality is working.
